name: Code Quality and Security Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install project dependencies
      run: |
        pip install -r requirements.txt

    - name: Install linters and security tools
      run: |
        pip install flake8 bandit

    - name: Run flake8 (Style Check)
      run: |
        echo "🧹 Ejecutando flake8 para estilo de código..."
        flake8 src/ --max-line-length=120 --statistics --exit-zero  # --exit-zero para no fallar el workflow (opcional)

    - name: Run Bandit (Security Scan)
      run: |
        echo "🛡️ Ejecutando bandit para escaneo de seguridad..."
        bandit -r src/ -c bandit.yml -f txt -o bandit-results.txt
