name: Deploy C4A Alerts Bot

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r cloud-function/requirements.txt

    - name: Run tests
      run: |
        python -m pytest tests/

    - name: Deploy to production
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        ADMIN_USER_ID: ${{ secrets.ADMIN_USER_ID }}
        ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}
        READ_ONLY_MODE: ${{ secrets.READ_ONLY_MODE }}
        C4A_API_URL: ${{ secrets.C4A_API_URL }}
        LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
        WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
        WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
      run: |
        echo "🚀 Desplegando C4A Alerts Bot..."
        echo "📊 Variables de entorno configuradas"
        echo "🔒 Modo de acceso: $READ_ONLY_MODE"
        echo "🌐 API URL: $C4A_API_URL"
        echo "👤 Admin ID: $ADMIN_USER_ID"
        echo "💬 Chat ID: $ADMIN_CHAT_ID"
