name: Export alerts CSV

on:
  schedule:
    - cron: '0 4 * * *'  # Todos los días a las 04:00 UTC
  workflow_dispatch:

jobs:
  export_csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install requirements (if any)
        run: pip install -r requirements.txt || true

      - name: Convert JSON to CSV
        run: python convert_history_to_csv.py

      - name: Commit and push CSV
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add alerts_history.csv
          git commit -m "🔄 Auto-export: alerts_history.csv actualizado" || echo "Sin cambios"
          git push
